runtime: python39

instance_class: F1
default_expiration: "30s"
entrypoint: gunicorn -b :$PORT -w 1 --threads 2 --disable-redirect-access-to-syslog main:app

automatic_scaling:
  max_concurrent_requests: 2
  max_instances: 1
  max_idle_instances: 1

handlers:
- url: /pyodide/(.*\.(wasm|data))$
  static_files: pyodide/\1
  upload: pyodide/.*\.(wasm|data)$
  mime_type: application/wasm
- url: /pyodide
  static_dir: pyodide

- url: /vi_plugins/s
  static_dir: vi_plugins
- url: /vi/s
  static_dir: vi

- url: /static
  static_dir: static
- url: /resources
  static_dir: viur/core/resources
- url: /favicon.ico
  static_files: static/meta/favicon.ico
  upload: favicon.ico
- url: /robots.txt
  static_files: static/meta/robots.txt
  upload: robots.txt

inbound_services:
- warmup

